# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tooltip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('is_activated', models.BooleanField(verbose_name='Is activated')),
                ('header', models.CharField(blank=True, max_length=255, null=True, verbose_name='Header')),
                ('text', models.TextField(null=True, verbose_name='Text')),
                ('placement', models.CharField(
                    choices=[('top', 'Top'), ('left', 'Left'), ('right', 'Right'), ('bottom', 'Bottom'), ('', 'Auto')],
                    blank=True, max_length=6, verbose_name='Placement')),
            ],
            options={
                'verbose_name_plural': 'Tooltips',
                'verbose_name': 'Tooltip',
            },
        ),
    ]
